---
version: "3.3"
services:
  db:
    image: dockerdeepak/workshop:pgdb_v1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - backend
    container_name: pgdb
  app:
    image: sshail/transaction:latest
    environment:
      - PORT=9085
      - DB_HOST=db
    #build: .
    networks:
      - backend
    depends_on:
      - db
    restart: always
    ports:
      - 8080:9085
    container_name: myapp
    
networks:
  backend:
    driver: bridge
